version: '3.6'
services:
  gateway:
    build:
      context: krakend
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./gateway:/etc/krakend
    ports:
      - 8080:8080
      - 80:8080
      - 443:8080
    command: [ "run", "-c", "/etc/krakend/config.json" ]
    depends_on:
    - identity
    - static_data
  static_data:
    image: jaxgeller/lwan
    container_name: 'static_data'
    volumes:
      - ./static_data:/lwan/wwwroot
    ports:
      - "8000:8080"
  identity:
    container_name: 'identity'
    image: 'identity'
    build:
      context: ./Identity
      dockerfile: development.dockerfile
    ports:
      - 5000:5000
  debug_api:
    container_name: 'debug_api'
    image: 'debug_api'
    build:
      context: ./debug_api
      dockerfile: Dockerfile
    ports:
      - 5001:5000